gg_rct_Fence_Zone = nil
gg_rct_Shepard_Respawn = nil
gg_rct_Pink_Start = nil
gg_rct_Green_Start = nil
gg_rct_Orange_Start = nil
gg_rct_Blue_Start = nil
gg_rct_Red_Start = nil
gg_rct_Purple_Start = nil
gg_rct_Yellow_Start = nil
gg_rct_grey_start = nil
gg_rct_lb_start = nil
gg_rct_dg_start = nil
gg_rct_brown_start = nil
gg_rct_pickfarm = nil
gg_rct_Teal_Start = nil
gg_rct_topShop1 = nil
gg_rct_bottomShop1 = nil
gg_rct_topShop2 = nil
gg_rct_bottomShop2 = nil
gg_rct_unstuckZone = nil
gg_rct_Rune_of_Invis = nil
gg_rct_Rune_of_Speed = nil
gg_rct_Rune_of_Mana = nil
gg_rct_Rune_of_Omniscience = nil
gg_rct_Maroon_Start = nil
gg_rct_Navy_Start = nil
gg_rct_Turquoise_Start = nil
gg_rct_Violet_Start = nil
gg_rct_Wheat_Start = nil
gg_rct_Peach_Start = nil
gg_rct_Mint_Start = nil
gg_rct_Lavender_Start = nil
gg_rct_Coal_Start = nil
gg_rct_Snow_Start = nil
gg_rct_Emerald_Start = nil
gg_rct_Peanut_Start = nil
gg_rct_Blight_Bot_1 = nil
gg_rct_Blight_Top_1 = nil
gg_rct_Blight_Left_1 = nil
gg_rct_Blight_Right_1 = nil
gg_rct_Blight_Top_2 = nil
gg_rct_Blight_Right_2 = nil
gg_rct_Blight_Bot_2 = nil
gg_rct_Blight_Left_2 = nil
gg_rct_Blight_Top_3 = nil
gg_rct_Blight_Left_3 = nil
gg_rct_Blight_Bot_3 = nil
gg_rct_Blight_Right_3 = nil
gg_rct_Blight_Top_4 = nil
gg_rct_Blight_Right_4 = nil
gg_rct_Blight_Left_4 = nil
gg_rct_Blight_Bot_4 = nil
gg_rct_Revo_Camera_Bounds = nil
gg_rct_Glory_Hill_Camera_Bounds = nil
gg_rct_Glory_Hill_Fence = nil
gg_rct_gh1 = nil
gg_rct_gh2 = nil
gg_rct_gh3 = nil
gg_rct_gh4 = nil
gg_rct_gh5 = nil
gg_rct_gh6 = nil
gg_rct_gh7 = nil
gg_rct_gh8 = nil
gg_rct_gh9 = nil
gg_rct_gh10 = nil
gg_rct_gh11 = nil
gg_rct_gh12 = nil
gg_rct_gh13 = nil
gg_rct_gh14 = nil
gg_rct_gh15 = nil
gg_rct_gh16 = nil
gg_rct_gh17 = nil
gg_rct_gh18 = nil
gg_rct_gh19 = nil
gg_rct_gh20 = nil
gg_rct_gh21 = nil
gg_rct_gh22 = nil
gg_rct_gh23 = nil
gg_rct_gh24 = nil
gg_rct_Glory_Hill_Spawn = nil
gg_rct_Glory_Hill_Invis = nil
gg_rct_Glory_Hill_Speed = nil
gg_rct_Glory_Hill_Omniscience = nil
gg_rct_Glory_Hill_Mana = nil
gg_rct_Glory_Hill_ShopA2 = nil
gg_rct_Glory_Hill_ShopB2 = nil
gg_rct_Glory_Hill_ShopA1 = nil
gg_rct_Glory_Hill_ShopB1 = nil
gg_rct_snowman = nil
gg_rct_topShop3 = nil
gg_rct_bottomShop3 = nil
gg_rct_Glory_Hill_ShopC1 = nil
gg_rct_Glory_Hill_ShopC2 = nil
gg_snd_GoodJob = nil
gg_snd_firstblood = nil
gg_snd_humiliation = nil
gg_snd_headshot = nil
gg_snd_DoubleKill = nil
gg_snd_Killionaire = nil
gg_snd_TripleKill = nil
gg_snd_Overkill = nil
gg_snd_ReceiveGold = nil
function InitGlobals()
end

function InitSounds()
gg_snd_GoodJob = CreateSound("Sound\\Interface\\GoodJob.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_GoodJob, 2548)
SetSoundChannel(gg_snd_GoodJob, 0)
SetSoundVolume(gg_snd_GoodJob, -1)
SetSoundPitch(gg_snd_GoodJob, 1.0)
gg_snd_firstblood = CreateSound("war3mapImported\\firstblood.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_firstblood, 1483)
SetSoundChannel(gg_snd_firstblood, 0)
SetSoundVolume(gg_snd_firstblood, 127)
SetSoundPitch(gg_snd_firstblood, 1.0)
gg_snd_humiliation = CreateSound("war3mapImported\\humiliation.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_humiliation, 1763)
SetSoundChannel(gg_snd_humiliation, 0)
SetSoundVolume(gg_snd_humiliation, 127)
SetSoundPitch(gg_snd_humiliation, 1.0)
gg_snd_headshot = CreateSound("war3mapImported\\headshot.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_headshot, 1277)
SetSoundChannel(gg_snd_headshot, 0)
SetSoundVolume(gg_snd_headshot, 127)
SetSoundPitch(gg_snd_headshot, 1.0)
gg_snd_DoubleKill = CreateSound("war3mapImported\\DoubleKill.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_DoubleKill, 1375)
SetSoundChannel(gg_snd_DoubleKill, 0)
SetSoundVolume(gg_snd_DoubleKill, 127)
SetSoundPitch(gg_snd_DoubleKill, 1.0)
gg_snd_Killionaire = CreateSound("war3mapImported\\Killionaire.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Killionaire, 1306)
SetSoundChannel(gg_snd_Killionaire, 0)
SetSoundVolume(gg_snd_Killionaire, 127)
SetSoundPitch(gg_snd_Killionaire, 1.0)
gg_snd_TripleKill = CreateSound("war3mapImported\\TripleKill.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_TripleKill, 1253)
SetSoundChannel(gg_snd_TripleKill, 0)
SetSoundVolume(gg_snd_TripleKill, 127)
SetSoundPitch(gg_snd_TripleKill, 1.0)
gg_snd_Overkill = CreateSound("war3mapImported\\Overkill.wav", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Overkill, 1253)
SetSoundChannel(gg_snd_Overkill, 0)
SetSoundVolume(gg_snd_Overkill, 127)
SetSoundPitch(gg_snd_Overkill, 1.0)
gg_snd_ReceiveGold = CreateSound("Abilities/Spells/Items/ResourceItems/ReceiveGold.flac", false, false, true, 1, 1, "SpellsEAX")
SetSoundParamsFromLabel(gg_snd_ReceiveGold, "ReceiveGold")
SetSoundDuration(gg_snd_ReceiveGold, 589)
SetSoundVolume(gg_snd_ReceiveGold, 127)
end

function CreateRegions()
local we

gg_rct_Fence_Zone = Rect(-608.0, -1376.0, 96.0, -544.0)
we = AddWeatherEffect(gg_rct_Fence_Zone, FourCC("LRaa"))
EnableWeatherEffect(we, true)
gg_rct_Shepard_Respawn = Rect(-288.0, -992.0, -224.0, -928.0)
gg_rct_Pink_Start = Rect(96.0, -192.0, 192.0, -96.0)
gg_rct_Green_Start = Rect(384.0, -832.0, 448.0, -736.0)
gg_rct_Orange_Start = Rect(352.0, -1248.0, 448.0, -1184.0)
gg_rct_Blue_Start = Rect(256.0, -1824.0, 320.0, -1728.0)
gg_rct_Red_Start = Rect(-288.0, -1792.0, -192.0, -1696.0)
gg_rct_Purple_Start = Rect(-800.0, -1792.0, -704.0, -1728.0)
gg_rct_Yellow_Start = Rect(-992.0, -768.0, -896.0, -704.0)
gg_rct_grey_start = Rect(-576.0, -192.0, -512.0, -96.0)
gg_rct_lb_start = Rect(-992.0, -320.0, -928.0, -256.0)
gg_rct_dg_start = Rect(-992.0, -1536.0, -928.0, -1440.0)
gg_rct_brown_start = Rect(512.0, -1600.0, 576.0, -1504.0)
gg_rct_pickfarm = Rect(-320.0, -2656.0, -160.0, -2496.0)
gg_rct_Teal_Start = Rect(-960.0, -1216.0, -896.0, -1120.0)
gg_rct_topShop1 = Rect(-448.0, 3904.0, -256.0, 4160.0)
gg_rct_bottomShop1 = Rect(-448.0, -5568.0, -256.0, -5312.0)
gg_rct_topShop2 = Rect(-256.0, 3904.0, -128.0, 4160.0)
gg_rct_bottomShop2 = Rect(-256.0, -5568.0, -128.0, -5312.0)
gg_rct_unstuckZone = Rect(-3840.0, -5536.0, -3552.0, -5344.0)
gg_rct_Rune_of_Invis = Rect(-576.0, -992.0, -480.0, -928.0)
gg_rct_Rune_of_Speed = Rect(-32.0, -992.0, 64.0, -928.0)
gg_rct_Rune_of_Mana = Rect(-288.0, -1312.0, -224.0, -1216.0)
gg_rct_Rune_of_Omniscience = Rect(-288.0, -704.0, -224.0, -608.0)
gg_rct_Maroon_Start = Rect(-960.0, -544.0, -864.0, -448.0)
gg_rct_Navy_Start = Rect(352.0, -448.0, 448.0, -352.0)
gg_rct_Turquoise_Start = Rect(-768.0, -224.0, -672.0, -128.0)
gg_rct_Violet_Start = Rect(480.0, -1440.0, 576.0, -1344.0)
gg_rct_Wheat_Start = Rect(448.0, -576.0, 512.0, -512.0)
gg_rct_Peach_Start = Rect(-320.0, -224.0, -224.0, -128.0)
gg_rct_Mint_Start = Rect(32.0, -1792.0, 128.0, -1696.0)
gg_rct_Lavender_Start = Rect(416.0, -992.0, 512.0, -896.0)
gg_rct_Coal_Start = Rect(-64.0, -224.0, 32.0, -128.0)
gg_rct_Snow_Start = Rect(-480.0, -1792.0, -384.0, -1728.0)
gg_rct_Emerald_Start = Rect(-992.0, -1408.0, -896.0, -1312.0)
gg_rct_Peanut_Start = Rect(-960.0, -992.0, -864.0, -896.0)
gg_rct_Blight_Bot_1 = Rect(-5376.0, -6016.0, 5760.0, -4480.0)
gg_rct_Blight_Top_1 = Rect(-5376.0, 3072.0, 5760.0, 4672.0)
gg_rct_Blight_Left_1 = Rect(-5376.0, -6016.0, -3904.0, 4672.0)
gg_rct_Blight_Right_1 = Rect(4096.0, -6016.0, 5760.0, 4672.0)
gg_rct_Blight_Top_2 = Rect(-3168.0, 2048.0, 3040.0, 3104.0)
gg_rct_Blight_Right_2 = Rect(3008.0, -3520.0, 4128.0, 3104.0)
gg_rct_Blight_Bot_2 = Rect(-3936.0, -4512.0, 4128.0, -3488.0)
gg_rct_Blight_Left_2 = Rect(-3936.0, -3520.0, -3136.0, 3104.0)
gg_rct_Blight_Top_3 = Rect(-3168.0, 1408.0, 3040.0, 2080.0)
gg_rct_Blight_Left_3 = Rect(-3168.0, -2848.0, -2624.0, 1440.0)
gg_rct_Blight_Bot_3 = Rect(-3168.0, -3520.0, 3040.0, -2816.0)
gg_rct_Blight_Right_3 = Rect(2112.0, -2848.0, 3040.0, 1440.0)
gg_rct_Blight_Top_4 = Rect(-2656.0, 768.0, 2144.0, 1440.0)
gg_rct_Blight_Right_4 = Rect(1408.0, -2848.0, 2144.0, 800.0)
gg_rct_Blight_Left_4 = Rect(-2656.0, -2848.0, -2080.0, 800.0)
gg_rct_Blight_Bot_4 = Rect(-2112.0, -2848.0, 1440.0, -2432.0)
gg_rct_Revo_Camera_Bounds = Rect(-4608.0, -5504.0, 4992.0, 4096.0)
gg_rct_Glory_Hill_Camera_Bounds = Rect(8800.0, -5504.0, 16992.0, 3200.0)
gg_rct_Glory_Hill_Fence = Rect(12576.0, -1376.0, 13280.0, -672.0)
we = AddWeatherEffect(gg_rct_Glory_Hill_Fence, FourCC("LRaa"))
EnableWeatherEffect(we, true)
gg_rct_gh1 = Rect(13568.0, -1344.0, 13632.0, -1280.0)
gg_rct_gh2 = Rect(12608.0, -1728.0, 12672.0, -1664.0)
gg_rct_gh3 = Rect(13184.0, -384.0, 13248.0, -320.0)
gg_rct_gh4 = Rect(12224.0, -768.0, 12288.0, -704.0)
gg_rct_gh5 = Rect(13184.0, -1728.0, 13248.0, -1664.0)
gg_rct_gh6 = Rect(12224.0, -1344.0, 12288.0, -1280.0)
gg_rct_gh7 = Rect(13568.0, -576.0, 13632.0, -512.0)
gg_rct_gh8 = Rect(12608.0, -384.0, 12672.0, -320.0)
gg_rct_gh9 = Rect(13568.0, -1728.0, 13632.0, -1664.0)
gg_rct_gh10 = Rect(12224.0, -1728.0, 12288.0, -1664.0)
gg_rct_gh11 = Rect(12224.0, -384.0, 12288.0, -320.0)
gg_rct_gh12 = Rect(13568.0, -192.0, 13632.0, -128.0)
gg_rct_gh13 = Rect(12896.0, -1728.0, 12960.0, -1664.0)
gg_rct_gh14 = Rect(13760.0, -864.0, 13824.0, -800.0)
gg_rct_gh15 = Rect(12032.0, -1056.0, 12096.0, -992.0)
gg_rct_gh16 = Rect(12896.0, -384.0, 12960.0, -320.0)
gg_rct_gh17 = Rect(13760.0, -1440.0, 13824.0, -1376.0)
gg_rct_gh18 = Rect(12032.0, -1440.0, 12096.0, -1376.0)
gg_rct_gh19 = Rect(12704.0, -1920.0, 12768.0, -1856.0)
gg_rct_gh20 = Rect(13280.0, -1920.0, 13344.0, -1856.0)
gg_rct_gh21 = Rect(12032.0, -672.0, 12096.0, -608.0)
gg_rct_gh22 = Rect(13280.0, -192.0, 13344.0, -128.0)
gg_rct_gh23 = Rect(13760.0, -288.0, 13824.0, -224.0)
gg_rct_gh24 = Rect(12512.0, -192.0, 12576.0, -128.0)
gg_rct_Glory_Hill_Spawn = Rect(12864.0, -1088.0, 12992.0, -960.0)
gg_rct_Glory_Hill_Invis = Rect(12640.0, -1088.0, 12768.0, -960.0)
gg_rct_Glory_Hill_Speed = Rect(13088.0, -1088.0, 13216.0, -960.0)
gg_rct_Glory_Hill_Omniscience = Rect(12864.0, -864.0, 12992.0, -736.0)
gg_rct_Glory_Hill_Mana = Rect(12864.0, -1312.0, 12992.0, -1184.0)
gg_rct_Glory_Hill_ShopA2 = Rect(16768.0, -960.0, 17024.0, -768.0)
gg_rct_Glory_Hill_ShopB2 = Rect(16768.0, -1088.0, 17024.0, -960.0)
gg_rct_Glory_Hill_ShopA1 = Rect(8448.0, -1216.0, 8704.0, -1024.0)
gg_rct_Glory_Hill_ShopB1 = Rect(8448.0, -1344.0, 8704.0, -1216.0)
gg_rct_snowman = Rect(416.0, 1888.0, 480.0, 1952.0)
gg_rct_topShop3 = Rect(-128.0, 3904.0, 64.0, 4160.0)
gg_rct_bottomShop3 = Rect(-128.0, -5568.0, 64.0, -5312.0)
gg_rct_Glory_Hill_ShopC1 = Rect(8448.0, -1536.0, 8704.0, -1344.0)
gg_rct_Glory_Hill_ShopC2 = Rect(16768.0, -1280.0, 17024.0, -1088.0)
end

function InitUpgrades_Player0()
SetPlayerTechResearched(Player(0), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(0), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player1()
SetPlayerTechResearched(Player(1), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(1), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player2()
SetPlayerTechResearched(Player(2), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(2), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player3()
SetPlayerTechResearched(Player(3), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(3), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player4()
SetPlayerTechResearched(Player(4), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(4), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player5()
SetPlayerTechResearched(Player(5), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(5), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player6()
SetPlayerTechResearched(Player(6), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(6), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player7()
SetPlayerTechResearched(Player(7), FourCC("Rhst"), 1)
SetPlayerTechResearched(Player(7), FourCC("Rhfl"), 1)
end

function InitUpgrades_Player8()
SetPlayerTechResearched(Player(8), FourCC("Rhst"), 1)
end

function InitUpgrades_Player9()
SetPlayerTechResearched(Player(9), FourCC("Rhst"), 1)
end

function InitUpgrades_Player10()
SetPlayerTechResearched(Player(10), FourCC("Rhst"), 1)
end

function InitUpgrades_Player11()
SetPlayerTechResearched(Player(11), FourCC("Rhst"), 1)
end

function InitUpgrades()
InitUpgrades_Player0()
InitUpgrades_Player1()
InitUpgrades_Player2()
InitUpgrades_Player3()
InitUpgrades_Player4()
InitUpgrades_Player5()
InitUpgrades_Player6()
InitUpgrades_Player7()
InitUpgrades_Player8()
InitUpgrades_Player9()
InitUpgrades_Player10()
InitUpgrades_Player11()
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(6), false)
SetPlayerController(Player(6), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(7), false)
SetPlayerController(Player(7), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(8), false)
SetPlayerController(Player(8), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(12), 12)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(12), false)
SetPlayerController(Player(12), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(13), 13)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(13), false)
SetPlayerController(Player(13), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(14), 14)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(14), false)
SetPlayerController(Player(14), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(15), 15)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(15), false)
SetPlayerController(Player(15), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(16), 16)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(17), 17)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(17), false)
SetPlayerController(Player(17), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(18), 18)
SetPlayerColor(Player(18), ConvertPlayerColor(18))
SetPlayerRacePreference(Player(18), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(18), false)
SetPlayerController(Player(18), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(19), 19)
SetPlayerColor(Player(19), ConvertPlayerColor(19))
SetPlayerRacePreference(Player(19), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(19), false)
SetPlayerController(Player(19), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(20), 20)
SetPlayerColor(Player(20), ConvertPlayerColor(20))
SetPlayerRacePreference(Player(20), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(20), false)
SetPlayerController(Player(20), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(21), 21)
SetPlayerColor(Player(21), ConvertPlayerColor(21))
SetPlayerRacePreference(Player(21), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(21), false)
SetPlayerController(Player(21), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(22), 22)
SetPlayerColor(Player(22), ConvertPlayerColor(22))
SetPlayerRacePreference(Player(22), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(22), false)
SetPlayerController(Player(22), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(23), 23)
SetPlayerColor(Player(23), ConvertPlayerColor(23))
SetPlayerRacePreference(Player(23), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(23), false)
SetPlayerController(Player(23), MAP_CONTROL_USER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(6), 0)
SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(7), 0)
SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(8), 0)
SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(9), 0)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(10), 0)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 0)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerTeam(Player(12), 1)
SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(13), 1)
SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(14), 1)
SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(15), 1)
SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 1)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(17), 1)
SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(18), 1)
SetPlayerState(Player(18), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(19), 1)
SetPlayerState(Player(19), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(20), 1)
SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(21), 1)
SetPlayerState(Player(21), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(22), 1)
SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(23), 1)
SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(22), true)
end

function main()
SetCameraBounds(-5120.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -5760.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 17664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 4352.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -5120.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 4352.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 17664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -5760.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
SetWaterBaseColor(255, 255, 255, 255)
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronWinterDay")
SetAmbientNightSound("LordaeronWinterNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateRegions()
InitUpgrades()
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_039")
SetMapDescription("TRIGSTR_041")
SetPlayers(24)
SetTeams(24)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -256.0, -1728.0)
DefineStartLocation(1, 320.0, -1792.0)
DefineStartLocation(2, -960.0, -1152.0)
DefineStartLocation(3, -768.0, -1728.0)
DefineStartLocation(4, -960.0, -704.0)
DefineStartLocation(5, 384.0, -1216.0)
DefineStartLocation(6, 384.0, -768.0)
DefineStartLocation(7, 128.0, -128.0)
DefineStartLocation(8, -576.0, -128.0)
DefineStartLocation(9, -960.0, -256.0)
DefineStartLocation(10, -960.0, -1472.0)
DefineStartLocation(11, 512.0, -1536.0)
DefineStartLocation(12, -896.0, -512.0)
DefineStartLocation(13, 384.0, -384.0)
DefineStartLocation(14, -704.0, -192.0)
DefineStartLocation(15, 512.0, -1408.0)
DefineStartLocation(16, 512.0, -512.0)
DefineStartLocation(17, -256.0, -192.0)
DefineStartLocation(18, 64.0, -1728.0)
DefineStartLocation(19, 448.0, -960.0)
DefineStartLocation(20, 0.0, -192.0)
DefineStartLocation(21, -448.0, -1728.0)
DefineStartLocation(22, -960.0, -1344.0)
DefineStartLocation(23, -896.0, -960.0)
InitCustomPlayerSlots()
InitCustomTeams()
end

